version: '3.3'

services:
  postgres:
    image: postgres:latest
    volumes:
      - pgdb:/var/lib/db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: url_shortener

volumes:
  pgdb:
